<a href="https://colab.research.google.com/github/Preethijenitha/Brain-Stock-Prediction/blob/main/brain_stroke_prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import pandas as pd
import numpy as np

In [4]:
a=pd.read_csv('/content/healthcare-dataset-stroke-data.csv.xls')
a

id  gender   age  hypertension  heart_disease ever_married  \
0      9046    Male  67.0             0              1          Yes   
1     51676  Female  61.0             0              0          Yes   
2     31112    Male  80.0             0              1          Yes   
3     60182  Female  49.0             0              0          Yes   
4      1665  Female  79.0             1              0          Yes   
...     ...     ...   ...           ...            ...          ...   
5105  18234  Female  80.0             1              0          Yes   
5106  44873  Female  81.0             0              0          Yes   
5107  19723  Female  35.0             0              0          Yes   
5108  37544    Male  51.0             0              0          Yes   
5109  44679  Female  44.0             0              0          Yes   

          work_type Residence_type  avg_glucose_level   bmi   smoking_status  \
0           Private          Urban             228.69  36.6  formerly smoked   
1     Self-employed          Rural             202.21   NaN     never smoked   
2           Private          Rural             105.92  32.5     never smoked   
3           Private          Urban             171.23  34.4           smokes   
4     Self-employed          Rural             174.12  24.0     never smoked   
...             ...            ...                ...   ...              ...   
5105        Private          Urban              83.75   NaN     never smoked   
5106  Self-employed          Urban             125.20  40.0     never smoked   
5107  Self-employed          Rural              82.99  30.6     never smoked   
5108        Private          Rural             166.29  25.6  formerly smoked   
5109       Govt_job          Urban              85.28  26.2          Unknown   

      stroke  
0          1  
1          1  
2          1  
3          1  
4          1  
...      ...  
5105       0  
5106       0  
5107       0  
5108       0  
5109       0  

[5110 rows x 12 columns]

In [5]:
a.columns


Index(['id', 'gender', 'age', 'hypertension', 'heart_disease', 'ever_married',
       'work_type', 'Residence_type', 'avg_glucose_level', 'bmi',
       'smoking_status', 'stroke'],
      dtype='object')

In [6]:
a.shape

(5110, 12)

In [7]:
a.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5110 entries, 0 to 5109
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   id                 5110 non-null   int64  
 1   gender             5110 non-null   object 
 2   age                5110 non-null   float64
 3   hypertension       5110 non-null   int64  
 4   heart_disease      5110 non-null   int64  
 5   ever_married       5110 non-null   object 
 6   work_type          5110 non-null   object 
 7   Residence_type     5110 non-null   object 
 8   avg_glucose_level  5110 non-null   float64
 9   bmi                4909 non-null   float64
 10  smoking_status     5110 non-null   object 
 11  stroke             5110 non-null   int64  
dtypes: float64(3), int64(4), object(5)
memory usage: 479.2+ KB


In [8]:
a.isnull().sum()

id                     0
gender                 0
age                    0
hypertension           0
heart_disease          0
ever_married           0
work_type              0
Residence_type         0
avg_glucose_level      0
bmi                  201
smoking_status         0
stroke                 0
dtype: int64

In [9]:
a.fillna(method='ffill',inplace=True)

/tmp/ipython-input-9-1870026900.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  a.fillna(method='ffill',inplace=True)


In [10]:
a.isnull().sum()

id                   0
gender               0
age                  0
hypertension         0
heart_disease        0
ever_married         0
work_type            0
Residence_type       0
avg_glucose_level    0
bmi                  0
smoking_status       0
stroke               0
dtype: int64

In [11]:
from sklearn import preprocessing
label_encoder=preprocessing.LabelEncoder()
a['gender']=label_encoder.fit_transform(a['gender'])
a['gender'].unique()

array([1, 0, 2])

In [12]:
label_encoder=preprocessing.LabelEncoder()
a['ever_married']=label_encoder.fit_transform(a['ever_married'])
a['ever_married'].unique()

array([1, 0])

In [13]:
label_encoder=preprocessing.LabelEncoder()
a['work_type']=label_encoder.fit_transform(a['work_type'])
a['work_type'].unique()

array([2, 3, 0, 4, 1])

In [14]:
label_encoder=preprocessing.LabelEncoder()
a['Residence_type']=label_encoder.fit_transform(a['Residence_type'])
a['Residence_type'].unique()

array([1, 0])

In [15]:
label_encoder=preprocessing.LabelEncoder()
a['smoking_status']=label_encoder.fit_transform(a['smoking_status'])
a['smoking_status'].unique()

array([1, 2, 3, 0])

In [16]:
x=a[['id', 'gender', 'age', 'hypertension', 'heart_disease', 'ever_married',
       'work_type', 'Residence_type', 'avg_glucose_level', 'bmi',
       'smoking_status']]
x

id  gender   age  hypertension  heart_disease  ever_married  \
0      9046       1  67.0             0              1             1   
1     51676       0  61.0             0              0             1   
2     31112       1  80.0             0              1             1   
3     60182       0  49.0             0              0             1   
4      1665       0  79.0             1              0             1   
...     ...     ...   ...           ...            ...           ...   
5105  18234       0  80.0             1              0             1   
5106  44873       0  81.0             0              0             1   
5107  19723       0  35.0             0              0             1   
5108  37544       1  51.0             0              0             1   
5109  44679       0  44.0             0              0             1   

      work_type  Residence_type  avg_glucose_level   bmi  smoking_status  
0             2               1             228.69  36.6               1  
1             3               0             202.21  36.6               2  
2             2               0             105.92  32.5               2  
3             2               1             171.23  34.4               3  
4             3               0             174.12  24.0               2  
...         ...             ...                ...   ...             ...  
5105          2               1              83.75  18.6               2  
5106          3               1             125.20  40.0               2  
5107          3               0              82.99  30.6               2  
5108          2               0             166.29  25.6               1  
5109          0               1              85.28  26.2               0  

[5110 rows x 11 columns]

In [17]:
y=a[['stroke']]
y

stroke
0          1
1          1
2          1
3          1
4          1
...      ...
5105       0
5106       0
5107       0
5108       0
5109       0

[5110 rows x 1 columns]

In [18]:
from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest=train_test_split(x,y,test_size=0.2)

In [19]:
xtrain.shape

(4088, 11)

In [20]:
xtest.shape

(1022, 11)

In [21]:
ytrain.shape

(4088, 1)

In [22]:
ytest.shape

(1022, 1)

In [23]:
from sklearn.metrics import accuracy_score
from sklearn.tree import DecisionTreeClassifier
b=DecisionTreeClassifier()
b.fit(xtrain,ytrain)
ypred=b.predict(xtest)
score=accuracy_score(ytest,ypred)
print(score)

0.9041095890410958


In [24]:
from sklearn.metrics import accuracy_score
from sklearn.naive_bayes import GaussianNB
b = GaussianNB()
b.fit(xtrain,ytrain)
ypred=b.predict(xtest)
score=accuracy_score(ytest,ypred)
print(score)

0.9187866927592955


/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [25]:
from sklearn.metrics import accuracy_score
from sklearn.ensemble import RandomForestClassifier
b = RandomForestClassifier(n_estimators=10)
b.fit(xtrain,ytrain)
ypred=b.predict(xtest)
score=accuracy_score(ytest,ypred)
print(score)

/usr/local/lib/python3.11/dist-packages/sklearn/base.py:1389: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)


0.9461839530332681


In [26]:
from sklearn.metrics import accuracy_score
from sklearn import svm
b = svm.SVC()
b.fit(xtrain,ytrain)
ypred=b.predict(xtest)
score=accuracy_score(ytest,ypred)
print(score)

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


0.9481409001956947


In [27]:
from sklearn.metrics import accuracy_score
from sklearn.linear_model import SGDClassifier
clf = SGDClassifier(loss="hinge", penalty="l2", max_iter=5)
b.fit(xtrain,ytrain)
ypred=b.predict(xtest)
score=accuracy_score(ytest,ypred)
print(score)

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


0.9481409001956947


In [28]:
prediction=b.predict([[9046,1,67.0,0,1,1,2,1,228.69,36.6,1]])
print(prediction)

[0]


/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but SVC was fitted with feature names
  warnings.warn(


In [29]:
prediction=b.predict([[44679,0,44.0,0,0,1,0,1,85.28,26.2,0]])
print(prediction)

[0]


/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but SVC was fitted with feature names
  warnings.warn(


In [30]:
prediction=b.predict([[60182,0,49.0,0,0,1,2,1,171.23,34.4,3]])
print(prediction)

[0]


/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but SVC was fitted with feature names
  warnings.warn(


In [31]:
from sklearn.metrics import confusion_matrix
c=confusion_matrix(ytest,ypred)
print(c)

[[969   0]
 [ 53   0]]


In [32]:
from sklearn.metrics import classification_report
print(classification_report(ytest,ypred))

              precision    recall  f1-score   support

           0       0.95      1.00      0.97       969
           1       0.00      0.00      0.00        53

    accuracy                           0.95      1022
   macro avg       0.47      0.50      0.49      1022
weighted avg       0.90      0.95      0.92      1022



/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
